### ISSUE TITLE
Accessibility & Dynamically switching selected tabs

### ISSUE THREAD

**Issue by oyeanuj** [pepjo/react-tabs-navigation#2]
Hi @pepjo! Thanks for the library! I was wondering if there were any plans in the short-term to make it a11y friendly and add keyboard navigation?

Additionally, I noticed that we can pass in the selected tab index. Does it allow us to also change the tabs dynamically - i.e. an action on tab can switch the tab to the other one?

**Comment by pepjo** [comment]
Hi @oyeanuj 😊 ! Yes, since now I'm done with my exams, I plan on doing keyboard navigation and improving old borwsers compatibility before christmas.

I'm not sure what you refer to exactly when you say "make it a11y friendly". I sure plan on implementing aria, is that what you are refering to?

No, right now the `selected` prop is only readed when first initiallized. You can use the private method for changing the tab if you want to (although it is subject to change). That method is `handleTabChange(tabIndex)` and accepts the index of the tab. I'll work on a public mehtod for the next update 😊.

**Comment by oyeanuj** [comment]
Thank you for the quick response!

> I'm not sure what you refer to exactly when you say "make it a11y friendly". I sure plan on implementing aria, is that what you are refering to?

Yes, and keyboard navigation. http://www.w3.org/TR/wai-aria-practices/#tabpanel

> 'll work on a public mehtod for the next update 😊.

Great, looking forward to it. Thank you!

**Comment by pepjo** [comment]
I have addressed all your issues with version 0.2.0 :smile:

tell me if you have other suggestions :smile:

**Comment by pepjo** [comment]
PD: About the changing the tab from inside the panel, if uploaded an example.

http://pepjo.github.io/react-tabs-navigation/ go the the tab "scroll" to see the button.

You can check out the source, however I do no recommend to use exactly the same code. If you want to communicate between child and parents you can use something like Flux :smile:

**Comment by oyeanuj** [comment]
Thanks for your quick work! Couple of things -
1. On upgrading, I am now getting a warning when I render the Tabs. 
   
   `Warning: `div` was passed a style object that has previously been mutated. Mutating `style` is deprecated. Consider cloning it beforehand. Check the `render` of `tabsNavigationMenu__tabs`. Previous style: {height: NaN}. Mutated style: {height: NaN}.`
2. For tab-switching, what do you think about this alternate idea - Developer ties 'selected' attribute to the state and modifying that changes the selected tab.

**Comment by pepjo** [comment]
I'll look into the first error.

```
For tab-switching, what do you think about this alternate idea - Developer ties 'selected' attribute to the state and modifying that changes the selected tab.
```

Yes, now modifing the `selected` prop should select the tab. So this should work now :smile:

**Comment by oyeanuj** [comment]
> I'll look into the first error.

Great, thank you!

I have another question, but not sure if it deserves opening another issue. So here goes (but let me know if you want me to) -

I like the idea of fixed tabs as we scroll. However, in my use-case, the tabs are part of another component and there are several of them in a page (think posts in Facebook, Twitter, for example). Now I'd love for the tabs to be fixed but only until the user is scrolling within that component (or post, in case of Fb, Twitter). In such a case, is it possible for the tabs to stay fixed only until the parent container hasn't scrolled past it? Coz otherwise, what happens is that even past that component, I have the tabs for that component showing.. 

Any thoughts would be most helpful!

Thanks again!

**Comment by pepjo** [comment]
I have corrected some minor issues, probably won't fix your issue. Would you be able to provide a case where this happens?

#### Setting the tabs to not fix

##### Current version

You can hide the tabs by setting `fixOffset` to at least `-(the height of the bar)`. You can even control 

##### Possible improvment

An improvement could be made in order to address your use case. This is not something I have the time to code now but contributions are welcome :smile:

Right now there are 2 behaviors: Fixed tabs and not fixed. This result in the situations 1, 2 and 4. If I have understood correctly you want a third behavior that replaces "fixed" when the element is scrolled away.

This new behavior would be 3. Relative bottom.

Probably it's not hard to implement, we just have to detect when the visible part of the component is the same as the tabs bar height. In that moment, all the content left on the screen would be underneath the tabs bar. Then, we just have to change the tabs bar style from "fixed" to "relative" and set bottom to 0. This will fix the bar to the bottom of the element and will scroll upwards with the component. This will also allow for a great and seamless transition.

If you cannot do it, then maybe I'll do it on February, if I have time then.

![Current tab behaviours](https://dl.dropboxusercontent.com/u/16886355/imatge-tabs-behaviour.png)

**Comment by pepjo** [comment]
I've corrected your warning: 
`Warning: 'div' was passed a style object that has previously been mutated. Mutating 'style' is deprecated. Consider cloning it beforehand. Check the 'render' of 'tabsNavigationMenu__tabs'. Previous style: {height: NaN}. Mutated style: {height: NaN}`

update to version 0.2.2 to correct this issue

**Comment by oyeanuj** [comment]
thank you, i'll check again! (sorry for disappearing on the thread!)
